language: python
install:
  - pip install -r requirements/ci.txt
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=manifest
before_script:
  - psql -d template1 -c 'create extension hstore;'
  - createuser -d -e hopper
  - createdb -U hopper hopper
script:
  - tox
sudo: false
notifications:
  slack:
    secure: VxOKr3ZnF/tTtYCfE/vynuzK/EEwpQBaxo854of5BNESFFciAKn+GMZpMiMT9BWtXTzwDKpxTl8G0qpBJ2lhxNODJ3LEl2GJVGCpGYCP9Y1NutMDDfy+siQc0RnZAKVViwJWCxeb1qSvaBErTNizSoCwyuAn+VgVJfTXUmtAlRU=
