language: python
install:
  - pip install -r requirements/ci.txt
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=manifest
addons:
  postgresql: 9.4
before_script:
  - createuser -S -d -R -e hopper
  - make create-db
script:
  - tox
after_success:
  - codecov
sudo: false
notifications:
  slack:
    secure: VxOKr3ZnF/tTtYCfE/vynuzK/EEwpQBaxo854of5BNESFFciAKn+GMZpMiMT9BWtXTzwDKpxTl8G0qpBJ2lhxNODJ3LEl2GJVGCpGYCP9Y1NutMDDfy+siQc0RnZAKVViwJWCxeb1qSvaBErTNizSoCwyuAn+VgVJfTXUmtAlRU=
